pyrene/src/components/TextField/TextField.jsx
Setting prop secret to true applies type 'password' to the input field, i.e. entered text will be obscured. Defaults to false, which will apply type 'text'.
=> [TextField] add secret prop (bool) for password field

.github/workflows/lint.yml, .github/workflows/test.yml, pyrene/package-lock.json, pyrene/package.json, pyrene/src/components/TimeRangeSelector/PresetTimeRanges/PresetTimeRanges.jsx, pyrene/src/components/TimeRangeSelector/TimeRangeNavigationBar/TimeRangeNavigationBar.jsx, pyrene/src/components/TimeRangeSelector/TimeRangeSelector.jsx
This PR removes all uses of `date-fns-tz` (except from test code). In my opinion, `date-fns-tz` actually complicates things significantly. From a time range point of view, there are no timezones, there's a start and end timestamp. So, the timezone only becomes relevant for display.
`Intl.DateTimeFormat` [1] handles this well. In my opinion, `date-fns-tz` can be useful to handle string to timestamp if a timezone is involved, i.e., figuring out the timestamp of "17 Mar 11:05".
If I understood things right, there's actually three timezones involved, local time, utc, and zoned time. Having the browser (or the tests) run in Europe/Zurich looks correct, using GMT though shows the discrepancy.
[1] https://caniuse.com/?search=DateTimeFormat
=> Fix time range selector timezones

.github/workflows/lint.yml, .github/workflows/test.yml, pyrene/package-lock.json, pyrene/package.json, pyrene/src/components/TimeRangeSelector/TimeRangeNavigationBar/TimeRangeNavigationBar.jsx
Follow-up of [PR](https://github.com/open-ch/pyrene/pull/6) merged on the 2021-04-12.
=> MC-21331 Intl.DateTimeFormat returns different format

pyrene/src/components/TreeTable/TreeTableHeader/treeTableHeader.css
=> MC-21315: Remove text-transform from TableHeader component

pyrene/src/components/TabView/TabView.examples.jsx, pyrene/src/components/TabView/TabView.jsx, pyrene/src/components/TabView/TabView.spec.jsx, pyrene/src/components/TabView/tabView.css
This PR is to extend the existing TabView component such that on the right side of tab name, some additional information could be displayed.
Visual effect:
I originally thought of an alternative approach, which is to make the current `name` prop and `nameRenderCallback` props mutually exclusive - if there is `name`, display the name; otherwise display the customizedly rendered name.
However, after many considerations I switched to the current approach where `name` is displayed no matter what and the additional section on the right side `nameRenderCallback` is optionally rendered.
The reasons are:
- it's backward compatible
- `name` is kinda used as `key` for this component, without the `name` prop we still would need to have something like `key` in its place
- it helps make the CSS more …
=> extended TabView to display extra section alongside tab name

pyrene/src/components/TreeTable/TreeTable.jsx
Thanks a lot for having a look at this PR!
The purpose of this PR is to expose a callback function when the columns are toggled for visibility such that the `columns` state could be used by the parent page.
Example use case: when there are multiple tables in different tabs (with TabView), switching to a different tab and then switching back to the original tab would reset all the selected columns in the table, so that user has to select the columns again, which can be quite much effort.
If you find this approach acceptable, I'm wondering maybe it's best that I extend the Table component similarly, so that the behaviors between tables are consistent?
Please let me know what you think :) Thanks a lot!
=> Added toggleColumnsCallback to TreeTable

pyrene/src/components/LabelAndValue/LabelAndValue.examples.tsx, pyrene/src/components/LabelAndValue/labelAndValue.css
=> Remove text-transform from LabelAndValue component

pyrene/src/components/KeyValueTable/KeyValueTable.examples.tsx, pyrene/src/components/KeyValueTable/keyValueTable.css
=> Remove text-transform from KeyValueTable component.

pyrene/src/components/Filter/FilterComponents/FilterTag.css
=> Remove text-transform from FilterTag component.

pyrene/src/components/TabView/tabView.css
Idea of this PR is to have the **props** capitalized in JS and not in CSS.
=> Remove text-transform from TabView component.

pyrene/DEVELOPMENT.md
The **Type** of the API of Pyerene component has to be exported.
If you do not export it, the linter complains. See example with `<TextAreaProps />`.
=> development documentation

pyrene/src/components/DropdownButton/dropdownButton.css
Nothing visible to show that the element is active (if selected with the tab button)
Using the :hover styling for the :focus so that component is highlighted once it receives focus from mouse hover or tab button
=> Add Focus Style to Dropdown Button

pyrene/src/components/MultiSelect/MultiSelect.jsx, pyrene/src/components/MultiSelect/multiSelectCSS.jsx
This implements the following changes in the `MultiSelect` component:
- `title` attribute is added to all value labels (so hovering over a truncated label will show the full one)
- the max width of a value label can be configured (previously hardcoded to `123px`)
Please let me know if you prefer a different API for this component or if the `title` attribute should not be added by default.
=> Improve multi value labels

pyrene/src/components/Modal/Modal.tsx, pyrene/src/components/Modal/modal.css
This allows a modal with scrolling content to take the full window height instead of the hardcoded max `512px`. So instead of always displaying the scrollbars (even if there is enough space left on the screen) it will now use this available space.
If the content is too large for the screen, it will fall back to display the scrollbar.
To make it backwards compatible and not change all existing modals, it is introduced as an additional property.
=> Allow modal with scrolling content to take full window height

kitchensink/src/app/data/foundationsData.jsx, kitchensink/src/app/static/foundations/ColorsPage.jsx
Change the 'Outage' label to 'Critical' in the kitchensink Colors page
=> Change Outage to Critical

pyrene/src/components/Badge/Badge.tsx, pyrene/src/components/CheckboxPopover/CheckboxList.tsx, pyrene/src/components/DropdownButton/OptionsItem.tsx, pyrene/src/components/DropdownButton/OptionsList.tsx, pyrene/src/components/Filter/Filter.tsx, pyrene/src/components/KeyValueTable/KeyValueTable.tsx, pyrene/src/components/Modal/Modal.examples.tsx, pyrene/src/components/Modal/Modal.tsx, pyrene/src/components/MultiSelect/MultiSelect.tsx, pyrene/src/components/RadioButton/RadioButton.tsx, pyrene/src/components/RadioGroup/RadioGroup.tsx, pyrene/src/components/SingleSelect/SingleSelect.tsx, pyrene/src/components/TimeRangeSelector/TimeRangeNavigationBar/ArrowSelector/TRSStepper/TRSStepper.tsx
1. Let the TS compiler do `type inference` on its own.
2. Fix bug happening while `clearing up` the input field filter introduced in [PR-176](https://github.com/open-ch/pyrene/pull/176/files) (`onChange`)
3. Stop unnecessary `call of void` `event handler`.
4. Remove useless `type of parameter` in FunctionComponent for non-public component.
5. `Nullish` operator
6. Remove useless `parenthesis`
=> code cleanup [improvement]

kitchensink/package.json
While running `npm run develop:pyene` in `kitchensink` we first have to install the dependencies at the root of the project. This fix was done in that [PR](https://github.com/open-ch/pyrene/pull/209).
There is still the problem remaining : 
> the dependencies of the root directory **depend** on the dependencies of the `pyrene` subproject.
=> dependencies install order [improvement]

pyrene/src/components/Accordion/Accordion.tsx, pyrene/src/components/Accordion/Section.tsx, pyrene/src/components/ArrowPopover/ArrowPopover.spec.tsx, pyrene/src/components/ArrowPopover/ArrowPopover.tsx, pyrene/src/components/Popover/Popover.tsx
- Fix `deprecated` type `ClientRect` (see screenshot)
- Type `reusability`
- Remove irrelevant `unit test` (already covered by static typing)
- Enhance syntax of TypeScript `interface`
=> typing remove unit test [improvement]

pyrene/src/components/ActionBar/ActionBar.tsx, pyrene/src/components/SimpleTable/SimpleTable.tsx, pyrene/src/components/TextArea/TextArea.tsx
- Get rid of unnecessary `any` in TS
- Get rid of unnecessary `checks` in boolean expression
- Get rid of irrelevant React `fragment`
- Get rid of `type duplication` (when an array is typed, the `elements` of it do not need to be typed again)
=> small enhancements [improvement]

pyrene/src/components/Badge/Badge.spec.tsx, pyrene/src/components/Badge/Badge.tsx, pyrene/src/components/Badge/badge.css
When `Badge` `onClick` function is defined, it shows a `pointer` cursor when hovered, otherwise it shows the default cursor
=> Feature: Badge shows pointer cursor when clickable

pyrene/src/components/Checkbox/Checkbox.tsx
There's complaint that 'You provided a `checked` prop to a form field without an `onChange` handler'. So the onChange function shouldn't be undefined.
=> used a function for onChange handler instead of undefined

pyrene/src/components/Table/Table.spec.jsx, pyrene/src/components/Table/Table.tsx
Sometimes some of the table actions need to be disabled conditionally. Existing uses of this component has been giving the 'active' a 'disabled' value, and this was OK before the TS conversion as 'disabled' didn't match the predefined 'single', 'multi'  and 'always' and will return a 'false', now with TS it's stricter and 'disabled' gets warning. So we might as well just add this as one of the allowed strings.
=> added 'disabled' state to table actions

pyrene/src/components/MultiSelect/MultiSelect.tsx
Sometimes the options are not available, so it shouldn't be a mandatory field. Also many of the existing uses of this component don't have options.
=> made multiselect options optional

pyrene/src/components/CheckboxPopover/CheckboxPopover.examples.ts
Fix the `example`, such that a click `revert` back to the initial state.
___
https://user-images.githubusercontent.com/6510794/143459298-39a98f74-db2a-4510-acd2-11005e2237ae.mov
=> checkbox popover click [bug]

pyrene/src/components/TreeTable/TreeTableCell/TreeTableCell.tsx
The misplacement of the `()` led to that the space holder was always there
=> fixed TreeTableCell display issue due to misplacement of '(' and ')'

pyrene/src/components/SingleSelect/select.css
We need to specify line height as 12px for select title (as we do for
other form components). I think the `height` that was set here was a
typo and it was meant to be `line-height` which is why I replaced that
property.
This is important because otherwise it will follow line height
of whatever parent element so it will certainly look weird most of the
time unlike the other form components that specify it
=> FIX: Select title line height

pyrene/src/components/MultiSelect/multiSelectCSS.jsx
We need to specify line height as 12px for select placeholder container (as we do for other form components).
This is important because otherwise it will follow line height of whatever parent element so it will certainly look weird most of the time unlike the other form components that specify it
=> FIX: multiselect placeholder alignment

eslint-config/index.js
This rule does not work properly with typescript, and typescript does this job already anyway.
So instead of disabling it in all projects separately, we can do that here in the global config if you agree.
=> Disable react/prop-types eslint rule for typescript

pyrene/src/components/MultiSelect/MultiSelect.tsx, pyrene/src/components/SingleSelect/SingleSelect.tsx
As discussed, extended the scope to include single select as both multi and single select implement the creatable prop which allows for the addition of new tags.
=> Fix Select "create new tag". label

pyrene/src/components/MultiSelect/MultiSelect.tsx, pyrene/src/components/SingleSelect/SingleSelect.tsx
Select component should not show "No match found" if Select component has no default options and is `creatable`.
=> Don't show "no match found"

pyrene/src/components/SingleSelect/SingleSelect.examples.tsx, pyrene/src/components/SingleSelect/SingleSelect.tsx
Extending the `SingleSelect` `value` property to support `null`.
This is useful for the case where we want to reset the value from another component (a button for example).
See the example component below (implemented in Storybook), containing a `SingleSelect` and a `Button` component:
When clicking on the button, we want the selected value to be cleared.
https://user-images.githubusercontent.com/15834481/151189454-8a42eeea-0160-4317-83ff-1d24d11a53bb.mov
(The example component is not part of this PR.)
=> Fix of SingleSelect clearing bug

pyrene/src/components/MultiSelect/MultiSelect.examples.ts, pyrene/src/components/MultiSelect/MultiSelect.tsx, pyrene/src/components/MultiSelect/delimiterUtil.spec.js, pyrene/src/components/MultiSelect/delimiterUtil.ts
Keep Default delimiters still as it is now.
Implement a prop such as `customDelimiters: ['\\s', ',', ';', '?']`
We want to make sure a user can type in 
- something, somethingelse and have 2 entries
- something somethingelse and have 2 entries
=> Multiselect input delimiter
