- pyrene/src/components/RadioGroup/RadioGroup.examples.tsx
- pyrene/src/components/RadioGroup/RadioGroup.tsx
- pyrene/src/components/RadioGroup/radioSelection.css
Added optional title to radiogroup element, as available for other form elements, such as textfield or textarea. Unlike radiobutton or checkbox, IMO radiogroup is a independent form element which often requires a title.
> [RadioGroup] add optional title

- pyrene-graphs/package-lock.json
- pyrene-graphs/package.json
- pyrene-graphs/src/components/Header/Header.jsx
- pyrene-graphs/src/components/SparkLineChart/SparkLineChart.jsx
- pyrene-graphs/src/components/Tooltip/Tooltip.jsx
- pyrene-graphs/src/components/Tooltip/TooltipLegendItem.jsx
Replace classnames module with clsx
> Configure clsx for pyrene-graphs

- pyrene/src/components/Filter/FilterOption/filterOption.css
- pyrene/src/components/TreeTable/TreeTable.examples.jsx
> MC-21315: Remove text-transform from FilterOption component.

- README.md
> Make pyrene logo work outside fo pyrene.

- pyrene-graphs/README.md
- pyrene/README.md
> Also add on subpackages..

- pyrene/src/components/TabView/TabView.jsx
While creating this PR there seems to be indications that there will be merge conflicts.🤷🏾‍♂️
> change styleName to className in TabView component

- CONTRIBUTING.md
- README.md
- SECURITY.md
- kitchensink/DEVELOPMENT.md
- kitchensink/README.md
- pyrene/DEVELOPMENT.md
- pyrene/README.md
A rough and simple suggestion for contributing guidelines.
Browse README, CONTRIBUTING, DEVELOPMENT files here:
https://github.com/neonnoon/pyrene/blob/feature/contributing/README.md
> Contributing Guidelines

- pyrene/DEVELOPMENT.md
This is happening without the displayName field.
> development documentation typescript

- eslint-config/index.js
- eslint-config/package-lock.json
- eslint-config/package.json
- kitchensink/.eslintrc
- kitchensink/package-lock.json
- kitchensink/package.json
- pyrene-graphs/package-lock.json
- pyrene-graphs/package.json
- pyrene/package-lock.json
- pyrene/package.json
- tuktuktwo/package-lock.json
- tuktuktwo/package.json
Cherry-picked change of #127 onto #11 (because that branch basically changes all of `package.json`), and prepared changes for actual update in packages.
Todo:
> Remove babel-eslint 

- kitchensink/package-lock.json
- kitchensink/package.json
- tuktuktwo/package-lock.json
- tuktuktwo/package.json
Fixes https://app.snyk.io/vuln/SNYK-JS-LODASH-1040724
> Update yup and vx

- pyrene/src/components/DateTimePicker/DateTimeInput/DateTimeInput.tsx
- pyrene/src/components/DateTimePicker/DateTimePicker.examples.tsx
- pyrene/src/components/DateTimePicker/DateTimePicker.tsx
- pyrene/src/components/DateTimePicker/ReactDatePickerWrapper/ReactDatePickerWrapper.tsx
Remark. Please in general let the TypeScript compiler do [type inference](https://www.typescriptlang.org/docs/handbook/type-inference.html).
> Datetimepicker-cleanup-thomas

- pyrene-graphs/package-lock.json
- pyrene-graphs/package.json
This should fix the display problems in the BarChartTable component by updating pyrene being used in pyrene-graphs
> Fix BarChartTable

- pyrene/src/components/Badge/Badge.spec.tsx
- pyrene/src/components/Badge/Badge.tsx
- pyrene/src/components/Badge/badge.css
> [badge] Add outage type to the badge component

- pyrene/src/components/TimeRangeSelector/TimeRangeNavigationBar/TimeRangeNavigationBar.jsx
See [documentation](https://github.com/marnusw/date-fns-tz#utctozonedtime).
> Unncessary type conversion

- kitchensink/src/app/common/PageElements/FoundationElements/ColorBox/colorBox.css
- kitchensink/src/app/common/PageElements/FoundationElements/ColorRow/ColorRow.jsx
- kitchensink/src/app/data/foundationsData.jsx
- kitchensink/src/app/static/foundations/ColorsPage.jsx
Dod:
Remove border from chart 3
Add color definition for Semantic Scheme
> Fix issues with Pyrene color page.

- pyrene/src/components/Filter/Filter.tsx
- pyrene/src/components/Filter/FilterComponents/FilterBar.tsx
- pyrene/src/components/Filter/FilterOption/FilterOption.tsx
- pyrene/src/components/Filter/types.ts
- pyrene/src/components/MultiSelect/MultiSelect.examples.ts
- pyrene/src/components/MultiSelect/MultiSelect.tsx
- pyrene/src/components/MultiSelect/types.ts
- pyrene/src/components/SingleSelect/SingleSelect.tsx
- pyrene/src/components/SingleSelect/SingleSelectTypes.ts
Proper `Filter` **type-check** completed.
> filter typing [improvement]

- pyrene/src/components/Form/Form.tsx
Fix warning introduced by [PR-173](https://github.com/open-ch/pyrene/pull/173) (see screenshot)
> form warning undefined props [BUG]

- pyrene/src/components/DateTimePicker/ReactDatePickerWrapper/ReactDatePickerWrapper.tsx
> [Fix] Fix typo

- kitchensink/src/app/common/ComponentPage.jsx
- kitchensink/src/app/common/PageElements/FoundationElements/IconDisplay/iconDisplay.css
- kitchensink/src/app/common/Search/ResultsPage.jsx
- kitchensink/src/app/static/IntroductionPage.jsx
- kitchensink/src/app/static/ResourcesPage.jsx
- kitchensink/src/app/static/cookBooks/FilterUsage.jsx
- kitchensink/src/app/static/cookBooks/FormUsage.jsx
- kitchensink/src/app/static/cookBooks/PyreneTutorial.jsx
- kitchensink/src/app/static/foundations/ColorsPage.jsx
- kitchensink/src/app/static/foundations/IconsPage.jsx
- kitchensink/src/app/static/foundations/TypographyPage.jsx
- kitchensink/src/app/static/howToPages/DateTimePicker.jsx
- kitchensink/src/css/componentPage.css
- kitchensink/src/css/propEditor.css
Cleaning up some CSS classes that do not have an implementation or are unused.
> Clean up unused styles

- pyrene/src/components/Button/Button.module.css
- pyrene/src/components/Button/Button.tsx
Allow setting of button width.
> Fix width button

- pyrene/src/components/Card/Card.tsx
- pyrene/src/components/Card/card.css
> Card Component Padding

- pyrene/src/components/Table/Table.examples.tsx
- pyrene/src/components/Table/Table.spec.jsx
- pyrene/src/components/Table/Table.tsx
https://user-images.githubusercontent.com/12200093/151340589-a02ff0d0-af82-4f2e-bfc8-56952ba59d58.mov
> Table action is active only if no rows are selected

- kitchensink/src/app/static/foundations/TypographyPage.jsx
- kitchensink/webpack.config.babel.js
- stories/texts.ts
- stories/typography.stories.mdx
Kitchensink and Storybook seem to work locally
> [fonts] Remove zipped fonts from repo

- pyrene/src/components/MultiSelect/MultiSelect.tsx
- pyrene/src/components/MultiSelect/delimiterUtil.ts
- pyrene/src/components/SingleSelect/SingleSelect.tsx
> Select should keep content when clicking outside
